name: CI/CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GHCR
        run: |
          docker login --username Kirixi --password ${{ secrets.GHRC_TOKEN }} ghcr.io

      - name: Build App Version 1 image
        run: |
          docker build . --tag ghcr.io/kirixi/app-version1:${GITHUB_SHA::7}
        working-directory: ./version1

      - name: Build App Version 2 image
        run: |
          docker build . --tag ghcr.io/kirixi/app-version2:${GITHUB_SHA::7}
        working-directory: ./version2

      - name: Build App Version 3 image
        run: |
          docker build . --tag ghcr.io/kirixi/app-version3:${GITHUB_SHA::7}
        working-directory: ./version3

      - name: Push the images into GHCR
        run: |
          docker push ghcr.io/kirixi/app-version1:${GITHUB_SHA::7}
          docker push ghcr.io/kirixi/app-version2:${GITHUB_SHA::7}
          docker push ghcr.io/kirixi/app-version3:${GITHUB_SHA::7}

  deploy-eks:
    runs-on: ubuntu-latest
    needs: [build-and-push]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Login to GHCR
        run: |
          docker login --username Kirixi --password ${{ secrets.GHRC_TOKEN }} ghcr.io

      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.REGION }}
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_KEY }}

      - name: Get kube config file
        run: aws eks update-kubeconfig --region ${{ secrets.REGION }} --name ${{ secrets.EKS_NAME }}

      - name: Deploy Version 1 with Helm
        uses: bitovi/github-actions-deploy-eks-helm@v1.2.10
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_KEY }}
          aws-region: ${{secrets.REGION }}
          cluster-name: ${{ secrets.EKS_NAME }}
          chart-path: k8s/apphelmcharts
          namespace: default
          values: imagetag=${{ env.SHORT_SHA }}
          name: app-version1

      - name: Deploy Version 2 with Helm
        uses: bitovi/github-actions-deploy-eks-helm@v1.2.10
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_KEY }}
          aws-region: ${{secrets.REGION }}
          cluster-name: ${{ secrets.EKS_NAME }}
          chart-path: k8s/version2-helmcharts
          namespace: default
          values: imagetag=${{ env.SHORT_SHA }}
          name: app-version2

      - name: Deploy Version 3 with Helm
        uses: bitovi/github-actions-deploy-eks-helm@v1.2.10
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_KEY }}
          aws-region: ${{secrets.REGION }}
          cluster-name: ${{ secrets.EKS_NAME }}
          chart-path: k8s/version3-helmcharts
          namespace: default
          values: imagetag=${{ env.SHORT_SHA }}
          name: app-version3
